apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
  labels:
    tier:
      name: rc1
spec:
  template:
    metadata: my-nginx-controller
    labels:
      tier:
        app: frontend
    spec:
      containers: 
        - name: my-nginx-container
          image: nginx    
  replicas: 2