apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    name: worker-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30006
  selector:
    name: worker-app-pod
    app: demo-voting-app  