apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pod-deploy
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
  selector:
    matchLabels:
     app: demo-voting-app
  replicas: 1   